{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/27/comments/73177593.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/diff/mjmm13/genomedata-py2_3-test:64b8f7c0c612..0bb1dda3fc3d?path=setup.py"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/27/_/diff#comment-73177593"}}, "parent": {"id": 73176760, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/27/comments/73176760.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/27/_/diff#comment-73176760"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 27, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/27.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/27"}}, "title": "Pipeline Update and Python 3 Compatibility"}, "content": {"raw": "ENOENT is correct, I had found the error number by looking for it, after receiving the error on the VM", "markup": "markdown", "html": "<p>ENOENT is correct, I had found the error number by looking for it, after receiving the error on the VM</p>", "type": "rendered"}, "created_on": "2018-08-16T14:55:27.352497+00:00", "user": {"display_name": "Matthew McNeil", "uuid": "{018cd21a-1658-4202-9b1e-99dabc3e14d0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B018cd21a-1658-4202-9b1e-99dabc3e14d0%7D"}, "html": {"href": "https://bitbucket.org/%7B018cd21a-1658-4202-9b1e-99dabc3e14d0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d7e7604c308bd957d77e1762b5caeddcd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMM-5.png"}}, "nickname": "mjmm13", "type": "user", "account_id": "5ac790531b5dd37ea53a123d"}, "inline": {"to": null, "from": null, "outdated": true, "path": "setup.py"}, "updated_on": "2018-08-16T14:55:27.364154+00:00", "type": "pullrequest_comment", "id": 73177593}