{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/genomedata/issues/27/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/genomedata/issues/27.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/27/watch"}, "comments": {"href": "data/repositories/hoffmanlab/genomedata/issues/27/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/27/attributeerror-file-object-has-no"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/27/vote"}}, "reporter": {"display_name": "Celia Siu", "uuid": "{f4f78e5d-281d-4996-b648-4d67a08891bb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bf4f78e5d-281d-4996-b648-4d67a08891bb%7D"}, "html": {"href": "https://bitbucket.org/%7Bf4f78e5d-281d-4996-b648-4d67a08891bb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/270b4fb6af77939368f91cd310490fa1d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCS-3.png"}}, "nickname": "celiasiu", "type": "user", "account_id": "557058:f3440d87-d636-439f-bc8c-53096f926849"}, "title": "AttributeError: 'File' object has no attribute 'createGroup' error upon running genomedata-load-seq", "component": null, "votes": 0, "watches": 1, "content": {"raw": "My end goal is to use Genomedata to convert my data into genomedata format for use in Segway, but ...\r\n\r\nWhen I run `genomedata-load-seq --verbose genomedata.test hg19.chr22.fa` (as a test because using all the chromosomes did not work), I get an AttributeError i.e.\r\n\r\n```\r\nImplementation unspecified. Found 1chromosomes/scaffolds, so using: dir\r\nhg19.chr22.fa\r\nTraceback (most recent call last):\r\n  File \"/home/csiu/anaconda2/envs/segway/bin/genomedata-load-seq\", line 6, in <module>\r\n    sys.exit(genomedata._load_seq.main())\r\n  File \"/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py\", line 319, in main\r\n    mode=options.mode, seqfile_type=options.seqfile_type)\r\n  File \"/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py\", line 261, in load_seq\r\n    read_seq(chromosome, seq)\r\n  File \"/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py\", line 133, in read_seq\r\n    seq_unambig, *span)\r\n  File \"/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py\", line 76, in create_supercontig\r\n    supercontig = h5file.createGroup(where, name)\r\nAttributeError: 'File' object has no attribute 'createGroup'\r\n```\r\nand I am unable to figure out why.\r\n\r\n----\r\n\r\n- I am using a Linux/Centos6 x86_64 system\r\n- genomedata was installed by using conda install segway. A relevant list of conda packages & versions include:\r\n```\r\npython                    2.7.12                        1  \r\nhdf5                      1.8.17                        6    conda-forge\r\nnumpy                     1.11.2                   py27_0  \r\ngenomedata                1.3.5                    py27_0    bioconda\r\n\r\ngmtk                      1.4.4                         0    bioconda\r\nsegway                    1.4.1                <egg_info>\r\n```\r\n\r\n- hg19.chr22.fa is produced by\r\n    1. Downloading hg19.2bit from http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/\r\n    2. And running `./twoBitToFa -seq=chr22 hg19.2bit hg19.chr22.fa` to produce the fasta. (twoBitToFa was download from [UCSC utilities](http://hgdownload.soe.ucsc.edu/admin/exe/))\r\n- I then ran `genomedata-load-seq --verbose genomedata.test hg19.chr22.fa` and got the above error\r\n- I tried removing the \"chr\" prefix from the sequence name, but the same error persists \r\n", "markup": "markdown", "html": "<p>My end goal is to use Genomedata to convert my data into genomedata format for use in Segway, but ...</p>\n<p>When I run <code>genomedata-load-seq --verbose genomedata.test hg19.chr22.fa</code> (as a test because using all the chromosomes did not work), I get an AttributeError i.e.</p>\n<div class=\"codehilite\"><pre><span></span>Implementation unspecified. Found 1chromosomes/scaffolds, so using: dir\nhg19.chr22.fa\nTraceback (most recent call last):\n  File &quot;/home/csiu/anaconda2/envs/segway/bin/genomedata-load-seq&quot;, line 6, in &lt;module&gt;\n    sys.exit(genomedata._load_seq.main())\n  File &quot;/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py&quot;, line 319, in main\n    mode=options.mode, seqfile_type=options.seqfile_type)\n  File &quot;/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py&quot;, line 261, in load_seq\n    read_seq(chromosome, seq)\n  File &quot;/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py&quot;, line 133, in read_seq\n    seq_unambig, *span)\n  File &quot;/home/csiu/anaconda2/envs/segway/lib/python2.7/site-packages/genomedata-1.3.5-py2.7.egg/genomedata/_load_seq.py&quot;, line 76, in create_supercontig\n    supercontig = h5file.createGroup(where, name)\nAttributeError: &#39;File&#39; object has no attribute &#39;createGroup&#39;\n</pre></div>\n\n\n<p>and I am unable to figure out why.</p>\n<hr />\n<ul>\n<li>I am using a Linux/Centos6 x86_64 system</li>\n<li>genomedata was installed by using conda install segway. A relevant list of conda packages &amp; versions include:</li>\n</ul>\n<div class=\"codehilite\"><pre><span></span>python                    2.7.12                        1  \nhdf5                      1.8.17                        6    conda-forge\nnumpy                     1.11.2                   py27_0  \ngenomedata                1.3.5                    py27_0    bioconda\n\ngmtk                      1.4.4                         0    bioconda\nsegway                    1.4.1                &lt;egg_info&gt;\n</pre></div>\n\n\n<ul>\n<li>hg19.chr22.fa is produced by<ol>\n<li>Downloading hg19.2bit from <a href=\"http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/\" rel=\"nofollow\" class=\"ap-connect-link\">http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/</a></li>\n<li>And running <code>./twoBitToFa -seq=chr22 hg19.2bit hg19.chr22.fa</code> to produce the fasta. (twoBitToFa was download from <a data-is-external-link=\"true\" href=\"http://hgdownload.soe.ucsc.edu/admin/exe/\" rel=\"nofollow\">UCSC utilities</a>)</li>\n</ol>\n</li>\n<li>I then ran <code>genomedata-load-seq --verbose genomedata.test hg19.chr22.fa</code> and got the above error</li>\n<li>I tried removing the \"chr\" prefix from the sequence name, but the same error persists </li>\n</ul>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2016-10-13T20:30:58.666428+00:00", "milestone": null, "updated_on": "2016-10-14T17:42:58.683079+00:00", "type": "issue", "id": 27}