{"priority": "critical", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/genomedata/issues/38/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/genomedata/issues/38.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/38/watch"}, "comments": {"href": "data/repositories/hoffmanlab/genomedata/issues/38/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/38/pytables-341-causes-a-core-dump-when"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/38/vote"}}, "reporter": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "title": "PyTables >= 3.4.1 causes a core dump when reading a continuous section from a supercontig", "component": null, "votes": 0, "watches": 1, "content": {"raw": "The following message is printed after an update on dependencies: \r\n\"Illegal instruction (core dumped)\"\r\n\r\nThis error is printed on the latest changeset (03e37b6cd731).\r\n\r\nHere is the log that caused the breakage to occur (when it did not previously):\r\n\r\n```\r\n#!bash\r\n\r\n$ pip install . --upgrade --user\r\nProcessing /mnt/work1/users/home2/eric.roberts/genomedata\r\nRequirement already up-to-date: numpy in /mnt/work1/users/home2/eric.roberts/.local/lib/python2.7/site-packages (from genomedata==1.3.6.dev0)\r\nRequirement already up-to-date: forked-path in /mnt/work1/software/python/2.7/lib/python2.7/site-packages (from genomedata==1.3.6.dev0)\r\nCollecting tables>=3.0 (from genomedata==1.3.6.dev0)\r\n  Using cached tables-3.4.2-cp27-cp27m-manylinux1_x86_64.whl\r\nRequirement already up-to-date: textinput in /mnt/work1/users/home2/eric.roberts/.local/lib/python2.7/site-packages (from genomedata==1.3.6.dev0)\r\nCollecting numexpr>=2.5.2 (from tables>=3.0->genomedata==1.3.6.dev0)\r\n  Using cached numexpr-2.6.2-cp27-cp27m-manylinux1_x86_64.whl\r\nRequirement already up-to-date: six>=1.9.0 in /mnt/work1/software/python/2.7/lib/python2.7/site-packages (from tables>=3.0->genomedata==1.3.6.dev0)\r\nInstalling collected packages: numexpr, tables, genomedata\r\n  Found existing installation: tables 3.3.0\r\n    Uninstalling tables-3.3.0:\r\n      Successfully uninstalled tables-3.3.0\r\n  Found existing installation: genomedata 1.3.6.dev0\r\n    Uninstalling genomedata-1.3.6.dev0:\r\n      Successfully uninstalled genomedata-1.3.6.dev0\r\n  Running setup.py install for genomedata ... done\r\nSuccessfully installed genomedata-1.3.6.dev0 numexpr-2.6.2 tables-3.4.2\r\n$ cd test/\r\n$ ./run_tests.py\r\nIllegal instruction (core dumped)\r\n\r\n```\r\n\r\nThis bug also occurs when trying to read from any valid Genomedata archive:\r\n\r\n\r\n```\r\n#!python\r\n\r\nfrom genomedata import Genome\r\ngenome = Genome(\"valid.genomedata\")\r\nchr1 = genome[\"chr1\"]\r\nsupercontig = chr1.supercontigs[0][0]\r\ncontinuous = supercontig.continuous\r\ncontinuous[0]\r\n```", "markup": "markdown", "html": "<p>The following message is printed after an update on dependencies: \n\"Illegal instruction (core dumped)\"</p>\n<p>This error is printed on the latest changeset (<a href=\"#!/hoffmanlab/genomedata/commits/03e37b6cd731\" rel=\"nofollow\" class=\"ap-connect-link\">03e37b6cd731</a>).</p>\n<p>Here is the log that caused the breakage to occur (when it did not previously):</p>\n<div class=\"codehilite language-bash\"><pre><span></span>$ pip install . --upgrade --user\nProcessing /mnt/work1/users/home2/eric.roberts/genomedata\nRequirement already up-to-date: numpy in /mnt/work1/users/home2/eric.roberts/.local/lib/python2.7/site-packages <span class=\"o\">(</span>from <span class=\"nv\">genomedata</span><span class=\"o\">==</span><span class=\"m\">1</span>.3.6.dev0<span class=\"o\">)</span>\nRequirement already up-to-date: forked-path in /mnt/work1/software/python/2.7/lib/python2.7/site-packages <span class=\"o\">(</span>from <span class=\"nv\">genomedata</span><span class=\"o\">==</span><span class=\"m\">1</span>.3.6.dev0<span class=\"o\">)</span>\nCollecting tables&gt;<span class=\"o\">=</span><span class=\"m\">3</span>.0 <span class=\"o\">(</span>from <span class=\"nv\">genomedata</span><span class=\"o\">==</span><span class=\"m\">1</span>.3.6.dev0<span class=\"o\">)</span>\n  Using cached tables-3.4.2-cp27-cp27m-manylinux1_x86_64.whl\nRequirement already up-to-date: textinput in /mnt/work1/users/home2/eric.roberts/.local/lib/python2.7/site-packages <span class=\"o\">(</span>from <span class=\"nv\">genomedata</span><span class=\"o\">==</span><span class=\"m\">1</span>.3.6.dev0<span class=\"o\">)</span>\nCollecting numexpr&gt;<span class=\"o\">=</span><span class=\"m\">2</span>.5.2 <span class=\"o\">(</span>from tables&gt;<span class=\"o\">=</span><span class=\"m\">3</span>.0-&gt;genomedata<span class=\"o\">==</span><span class=\"m\">1</span>.3.6.dev0<span class=\"o\">)</span>\n  Using cached numexpr-2.6.2-cp27-cp27m-manylinux1_x86_64.whl\nRequirement already up-to-date: six&gt;<span class=\"o\">=</span><span class=\"m\">1</span>.9.0 in /mnt/work1/software/python/2.7/lib/python2.7/site-packages <span class=\"o\">(</span>from tables&gt;<span class=\"o\">=</span><span class=\"m\">3</span>.0-&gt;genomedata<span class=\"o\">==</span><span class=\"m\">1</span>.3.6.dev0<span class=\"o\">)</span>\nInstalling collected packages: numexpr, tables, genomedata\n  Found existing installation: tables <span class=\"m\">3</span>.3.0\n    Uninstalling tables-3.3.0:\n      Successfully uninstalled tables-3.3.0\n  Found existing installation: genomedata <span class=\"m\">1</span>.3.6.dev0\n    Uninstalling genomedata-1.3.6.dev0:\n      Successfully uninstalled genomedata-1.3.6.dev0\n  Running setup.py install <span class=\"k\">for</span> genomedata ... <span class=\"k\">done</span>\nSuccessfully installed genomedata-1.3.6.dev0 numexpr-2.6.2 tables-3.4.2\n$ <span class=\"nb\">cd</span> test/\n$ ./run_tests.py\nIllegal instruction <span class=\"o\">(</span>core dumped<span class=\"o\">)</span>\n</pre></div>\n\n\n<p>This bug also occurs when trying to read from any valid Genomedata archive:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"kn\">from</span> <span class=\"nn\">genomedata</span> <span class=\"kn\">import</span> <span class=\"n\">Genome</span>\n<span class=\"n\">genome</span> <span class=\"o\">=</span> <span class=\"n\">Genome</span><span class=\"p\">(</span><span class=\"s2\">&quot;valid.genomedata&quot;</span><span class=\"p\">)</span>\n<span class=\"n\">chr1</span> <span class=\"o\">=</span> <span class=\"n\">genome</span><span class=\"p\">[</span><span class=\"s2\">&quot;chr1&quot;</span><span class=\"p\">]</span>\n<span class=\"n\">supercontig</span> <span class=\"o\">=</span> <span class=\"n\">chr1</span><span class=\"o\">.</span><span class=\"n\">supercontigs</span><span class=\"p\">[</span><span class=\"mi\">0</span><span class=\"p\">][</span><span class=\"mi\">0</span><span class=\"p\">]</span>\n<span class=\"n\">continuous</span> <span class=\"o\">=</span> <span class=\"n\">supercontig</span><span class=\"o\">.</span><span class=\"n\">continuous</span>\n<span class=\"n\">continuous</span><span class=\"p\">[</span><span class=\"mi\">0</span><span class=\"p\">]</span>\n</pre></div>", "type": "rendered"}, "assignee": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2017-04-25T19:29:17.434780+00:00", "milestone": null, "updated_on": "2017-06-07T14:59:44.674952+00:00", "type": "issue", "id": 38}