{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/genomedata/issues/39/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/genomedata/issues/39.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/39/watch"}, "comments": {"href": "data/repositories/hoffmanlab/genomedata/issues/39/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/39/seqfile_type-is-none-on-genomedata-load"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/39/vote"}}, "reporter": null, "title": "seqfile_type is None on genomedata-load-seq", "component": null, "votes": 0, "watches": null, "content": {"raw": "Hello! I wanted to start by saying that I really like the API of this program, which is why I'm a little disappointed that I'm having trouble getting it working. \r\n\r\nI'm attempting to run the genome-load-seq operation, as all I really need from this is the sequence retrieval. However, when I pass in the command **genomedata-load-seq -d ./genomearchive ./TriTrypDB-32_LmajorFriedlin_Genome.fasta**, I'm met with an error reporting an AssertionError on the statement assert seqfile_type in frozenset([\"agp\", \"fasta\"])\r\n\r\nThis is strange, as I looked in the file _load_seq.py and it seems that seqfile_type is actually an argument passed to the load_seq python method, and is set with a default argument. However, when I added the 'print(seqfile_type)' line just before the assert line and run the command again, I find that None is printed just before the error.\r\n\r\nNothing in the method before that changes the attribute so far as I can tell, so what's happening?\r\n\r\nYou can reach me at mullencr@miamioh.edu, I don't have an account here.", "markup": "markdown", "html": "<p>Hello! I wanted to start by saying that I really like the API of this program, which is why I'm a little disappointed that I'm having trouble getting it working. </p>\n<p>I'm attempting to run the genome-load-seq operation, as all I really need from this is the sequence retrieval. However, when I pass in the command <strong>genomedata-load-seq -d ./genomearchive ./TriTrypDB-32_LmajorFriedlin_Genome.fasta</strong>, I'm met with an error reporting an AssertionError on the statement assert seqfile_type in frozenset([\"agp\", \"fasta\"])</p>\n<p>This is strange, as I looked in the file _load_seq.py and it seems that seqfile_type is actually an argument passed to the load_seq python method, and is set with a default argument. However, when I added the 'print(seqfile_type)' line just before the assert line and run the command again, I find that None is printed just before the error.</p>\n<p>Nothing in the method before that changes the attribute so far as I can tell, so what's happening?</p>\n<p>You can reach me at mullencr@miamioh.edu, I don't have an account here.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2017-06-29T17:26:41.385031+00:00", "milestone": null, "updated_on": "2017-07-05T20:52:05.945067+00:00", "type": "issue", "id": 39}