{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/44/comments/43415745.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/44#comment-43415745"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/44.json"}}, "type": "issue", "id": 44, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Installation problem"}, "content": {"raw": "Hello,\n\nIs there any error messages above? I cannot reproduce this error on Python 2.7. I *can* however reproduce this bug with Python 3. \n\nIs get the following message above your exact error:\n\n```python\n    Complete output from command python setup.py egg_info:\n    Genomedata requires Python version 2.7+\n```\n\nPlease ensure that you're installing on Python 2.7. Python 3 support is planned in the future. If you're still having the issue please report back.", "markup": "markdown", "html": "<p>Hello,</p>\n<p>Is there any error messages above? I cannot reproduce this error on Python 2.7. I <em>can</em> however reproduce this bug with Python 3. </p>\n<p>Is get the following message above your exact error:</p>\n<div class=\"codehilite language-python\"><pre><span></span>    <span class=\"n\">Complete</span> <span class=\"n\">output</span> <span class=\"kn\">from</span> <span class=\"nn\">command</span> <span class=\"nn\">python</span> <span class=\"nn\">setup.py</span> <span class=\"nn\">egg_info</span><span class=\"p\">:</span>\n    <span class=\"n\">Genomedata</span> <span class=\"n\">requires</span> <span class=\"n\">Python</span> <span class=\"n\">version</span> <span class=\"mf\">2.7</span><span class=\"o\">+</span>\n</pre></div>\n\n\n<p>Please ensure that you're installing on Python 2.7. Python 3 support is planned in the future. If you're still having the issue please report back.</p>", "type": "rendered"}, "created_on": "2018-02-20T13:38:03.180675+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": null, "type": "issue_comment", "id": 43415745}