{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/50/comments/49729175.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/50#comment-49729175"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/50.json"}}, "type": "issue", "id": 50, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "pip install --upgrade genomedata can fail on some systems, due to path.py issues"}, "content": {"raw": "Thanks for those details! I don't have a better idea either, except perhaps the genomedata installation checking for and warning about an existing \"forked-`path`\" package.", "markup": "markdown", "html": "<p>Thanks for those details! I don't have a better idea either, except perhaps the genomedata installation checking for and warning about an existing \"forked-<code>path</code>\" package.</p>", "type": "rendered"}, "created_on": "2019-01-03T21:32:01.806916+00:00", "user": {"display_name": "Coby Viner", "uuid": "{5c0277b2-d18f-432a-9ff0-3377d3063bd6}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5c0277b2-d18f-432a-9ff0-3377d3063bd6%7D"}, "html": {"href": "https://bitbucket.org/%7B5c0277b2-d18f-432a-9ff0-3377d3063bd6%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/30ee4699432a3591c043fbe3d4bff771d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCV-5.png"}}, "nickname": "cviner2", "type": "user", "account_id": "557058:278c659b-177a-486c-bf20-6982986d7e43"}, "updated_on": "2019-01-03T21:33:04.846565+00:00", "type": "issue_comment", "id": 49729175}